### ISSUE TITLE
Investigate upgrading to Iris 2

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#215]
As an Improver developer I want to investigate upgrading to Iris 2 so that I can later upgrade, stay up to date and take advantage of exciting new technologies such as Dask.

Acceptance criteria:
* Update site-specific script to load Iris 2 module
* Investigate and fix errors in unit tests and CLI acceptance tests under Iris 2
* Spend no more than 8 days on this
* If all errors fixed:
  * Update Travis .travis.yml and environment.yml files to reflect Iris 2 equivalents.
  * Porting IMPROVER code to Dask is out of scope
* Raise an issue for follow-up work including errors left, to also include:

Follow-up work:
* Investigate which coding patterns in plug-ins break data laziness
* Provide an overview of which plugs-ins are currently working in a lazy manner (i.e., return a cube with lazy data if they got one as input) and which require modification or rewrite

**Comment by benfitzpatrick** [comment]
Existing failures:
```
FAIL: test_temperature_data_check (improver.tests.ensemble_calibration.ensemble_calibration.test_EnsembleCalibration.Test_process)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "improver/tests/ensemble_calibration/ensemble_calibration/test_EnsembleCalibration.py", line 173, in test_temperature_data_check
    self.assertArrayAlmostEqual(result[0][0].data, predictor_data)
  File "/opt/lib/python/iris/tests/__init__.py", line 614, in assertArrayAlmostEqual
    np.testing.assert_array_almost_equal(a, b, decimal=decimal)
  File "/opt/lib/python/numpy/testing/utils.py", line 962, in assert_array_almost_equal
    precision=decimal)
  File "/opt/lib/python/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: array([[ 229.483333,  240.733333,  251.983333],
       [ 263.233333,  274.483333,  285.733333],
       [ 296.983333,  308.233333,  319.483333]])
 y: array([[ 231.150029,  242.40003 ,  253.650031],
       [ 264.900033,  276.150034,  287.400035],
       [ 298.650036,  309.900038,  321.150039]])

======================================================================
FAIL: test_temperature_members_data_check (improver.tests.ensemble_calibration.ensemble_calibration.test_EnsembleCalibration.Test_process)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "improver/tests/ensemble_calibration/ensemble_calibration/test_EnsembleCalibration.py", line 221, in test_temperature_members_data_check
    self.assertArrayAlmostEqual(result[0][0].data, predictor_data)
  File "/opt/lib/python/iris/tests/__init__.py", line 614, in assertArrayAlmostEqual
    np.testing.assert_array_almost_equal(a, b, decimal=decimal)
  File "/opt/lib/python/numpy/testing/utils.py", line 962, in assert_array_almost_equal
    precision=decimal)
  File "/opt/lib/python/numpy/testing/utils.py", line 715, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals

(shapes (3, 3, 3), (3, 3) mismatch)
 x: array([[[ 226.15,  237.4 ,  248.65],
        [ 259.9 ,  271.15,  282.4 ],
        [ 293.65,  304.9 ,  316.15]],...
 y: array([[ 230.536599,  241.803634,  253.070668],
       [ 264.337703,  275.604738,  286.871772],
       [ 298.138807,  309.405842,  320.672876]])

======================================================================
FAIL: test_wind_speed_data_check (improver.tests.ensemble_calibration.ensemble_calibration.test_EnsembleCalibration.Test_process)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "improver/tests/ensemble_calibration/ensemble_calibration/test_EnsembleCalibration.py", line 248, in test_wind_speed_data_check
    self.assertArrayAlmostEqual(result[0][0].data, predictor_data)
  File "/opt/lib/python/iris/tests/__init__.py", line 614, in assertArrayAlmostEqual
    np.testing.assert_array_almost_equal(a, b, decimal=decimal)
  File "/opt/lib/python/numpy/testing/utils.py", line 962, in assert_array_almost_equal
    precision=decimal)
  File "/opt/lib/python/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: array([[  2. ,   9.5,  17. ],
       [ 24.5,  32. ,  39.5],
       [ 47. ,  54.5,  62. ]])
 y: array([[  2.999986,  10.499988,  17.99999 ],
       [ 25.499992,  32.999994,  40.499997],
       [ 47.999999,  55.500001,  63.000003]])

======================================================================
FAIL: test_wind_speed_members_data_check (improver.tests.ensemble_calibration.ensemble_calibration.test_EnsembleCalibration.Test_process)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "improver/tests/ensemble_calibration/ensemble_calibration/test_EnsembleCalibration.py", line 296, in test_wind_speed_members_data_check
    self.assertArrayAlmostEqual(result[0][0].data, predictor_data)
  File "/opt/lib/python/iris/tests/__init__.py", line 614, in assertArrayAlmostEqual
    np.testing.assert_array_almost_equal(a, b, decimal=decimal)
  File "/opt/lib/python/numpy/testing/utils.py", line 962, in assert_array_almost_equal
    precision=decimal)
  File "/opt/lib/python/numpy/testing/utils.py", line 715, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals

(shapes (3, 3, 3), (3, 3) mismatch)
 x: array([[[  0. ,   7.5,  15. ],
        [ 22.5,  30. ,  37.5],
        [ 45. ,  52.5,  60. ]],...
 y: array([[  2.057999,   9.734702,  17.411405],
       [ 25.088108,  32.764811,  40.441514],
       [ 48.118217,  55.79492 ,  63.471622]])

======================================================================
FAIL: test_coefficient_values_for_fake_distribution (improver.tests.ensemble_calibration.ensemble_calibration.test_EstimateCoefficientsForEnsembleCalibration.Test_estimate_coefficients_for_ngr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "improver/tests/ensemble_calibration/ensemble_calibration/test_EstimateCoefficientsForEnsembleCalibration.py", line 535, in test_coefficient_values_for_fake_distribution
    current_forecast, historic_forecasts, truth)
AssertionError: KeyError not raised

======================================================================
FAIL: test_coordinate_not_found (improver.tests.nbhood.use_nbhood.test_CollapseMaskedNeighbourhoodCoordinate.Test_renormalize_weights)
Coordinate not found on the cube.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "improver/tests/nbhood/use_nbhood/test_CollapseMaskedNeighbourhoodCoordinate.py", line 203, in test_coordinate_not_found
    plugin.renormalize_weights(nbhooded_cube)
AssertionError: "Expected to find exactly 1  coordinate, but found none." does not match "'Expected to find exactly 1 kitten coordinate, but found none.'"

======================================================================
FAIL: test_exception_when_coord_not_found (improver.tests.blending.blend_across_adjacent_points.test_TriangularWeightedBlendAcrossAdjacentPoints.Test_correct_collapsed_coordinates)
Test that an exception is raised by Iris when we try to correct
----------------------------------------------------------------------
Traceback (most recent call last):
  File "improver/tests/blending/blend_across_adjacent_points/test_TriangularWeightedBlendAcrossAdjacentPoints.py", line 199, in test_exception_when_coord_not_found
    ['forecast_period'])
AssertionError: "Expected to find exactly 1  coordinate, but found none." does not match "'Expected to find exactly 1 forecast_period coordinate, but found none.'"

======================================================================
FAIL: test_wrong_size_coords (improver.tests.blending.blend_across_adjacent_points.test_TriangularWeightedBlendAcrossAdjacentPoints.Test_correct_collapsed_coordinates)
Test it raises an error when new_cube and old_cube have
----------------------------------------------------------------------
Traceback (most recent call last):
  File "improver/tests/blending/blend_across_adjacent_points/test_TriangularWeightedBlendAcrossAdjacentPoints.py", line 189, in test_wrong_size_coords
    ['forecast_period'])
AssertionError: "New points shape must match existing points shape." does not match "Require data with shape (3,), got (2,)."

======================================================================
FAIL: test_fails_coord_not_in_cube (improver.tests.blending.weighted_blend.test_WeightedBlendAcrossWholeDimension.Test_process)
Test it raises CoordinateNotFoundError if coord not in the cube.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "improver/tests/blending/weighted_blend/test_WeightedBlendAcrossWholeDimension.py", line 168, in test_fails_coord_not_in_cube
    plugin.process(self.cube)
AssertionError: "Expected to find exactly 1  coordinate, but found none." does not match "'Expected to find exactly 1 notset coordinate, but found none.'"

======================================================================
FAIL: test_updated_metadata (improver.tests.wind_gust_diagnostic.test_WindGustDiagnostic.Test_update_metadata_after_max)
Test that the metadata is set as expected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "improver/tests/wind_gust_diagnostic/test_WindGustDiagnostic.py", line 173, in test_updated_metadata
    result.coord(self.perc_coord)
AssertionError: "Expected to find exactly 1  coordinate, but found none." does not match "'Expected to find exactly 1 percentile_over_nbhood coordinate, but found none.'"

----------------------------------------------------------------------
Ran 1243 tests in 49.885s

FAILED (failures=10)
```

**Comment by MoseleyS** [comment]
I believe the above results can be obtained by changing the `scitools `module to `experimental-current` in your local `etc/site-init` file before running the standard improver tests. Running this today yields 14 failures, not 10.
